apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  env.js: |
    window.ENV = {
      PRODUCT_API_URL: "http://product-service:8000",
      ORDER_API_URL: "http://order-service:8001",
      CUSTOMER_API_URL: "http://customer-service:8002"
    };
