apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  env.js: |
    window.ENV = {
      PRODUCT_API_URL: "/api/products",
      ORDER_API_URL: "/api/orders",
      CUSTOMER_API_URL: "/api/customers"
    };