apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri /index.html;
        }

        location /api/products {
            proxy_pass http://product-service:8000/products;
        }

        location /api/orders {
            proxy_pass http://order-service:8001/orders;
        }

        location /api/customers {
            proxy_pass http://customer-service:8002/customers;
        }
    }