name: CD - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: sit722aks
          resource-group: 10.2d-rg
          subscription: ae0eb9b3-af99-4afb-928d-ea541a145e0e
          admin: true

      - name: Ensure production namespace exists
        run: |
          kubectl create namespace production || true

      - name: Deploy to Production
        run: |
          kubectl apply -n production -f k8s/

      - name: Restart Deployments to pull latest images
        run: |
          kubectl rollout restart deployment/frontend -n production
          kubectl rollout restart deployment/product-service -n production
          kubectl rollout restart deployment/order-service -n production
          kubectl rollout restart deployment/customer-service -n production