name: CD Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: 10.2d-rg
      CLUSTER_NAME: sit722aks
      NAMESPACE: sit722-prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

    - name: Deploy all manifests to Production
      run: |
        kubectl apply -f k8s/production/