name: CD - Deploy to Staging

on:
  workflow_run:
    workflows: ["CI - Build and Push Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: sit722aks
          resource-group: 10.2d-rg

      - name: Deploy to Staging
        run: |
          kubectl apply -n staging -f k8s/

      - name: Restart Deployments to pull latest images
        run: |
          kubectl rollout restart deployment/frontend -n staging
          kubectl rollout restart deployment/product-service -n staging
          kubectl rollout restart deployment/order-service -n staging
          kubectl rollout restart deployment/customer-service -n staging